name: scattering-dev
channels:
 - conda-forge
dependencies:
 - mdtraj>=1.9.6
 - numpy
 - progressbar2
 - scipy
 - codecov
 - bump2version
 - pytest
 - pytest-azurepipelines
 - pytest-cov
 - python<=3.8
